### ISSUE TITLE
Swap from/to showing wrong exchange direction

### ISSUE THREAD

**Issue by wildpig** [fck-team/dyor_bug_tracker#1]
_Swap from_ shows Fish Memecoin and _Swap to_ Ton while acctually I swapped from Ton to Fish Memecoin. 
![fish-ton](https://github.com/fck-team/dyor_bug_tracker/assets/3748400/78a42f1c-81e8-40b9-9287-dea1c8545860)

**Comment by BeyCoder** [comment]
fixed
